# Generated by Django 5.2.3 on 2025-06-28 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='your_name',
            field=models.CharField(default='Anonimo', max_length=400, validators=[django.core.validators.MinLengthValidator(3, 'Valor de caracteres menor que o permitido "(3)", coloque um valor válido.'), django.core.validators.MaxLengthValidator(400, 'Valor de caracteres maior que o permitido "(400)", coloque um valor válido.')]),
        ),
    ]
